- name: declare a variable
  hosts: all
  vars:
    url: example.com
    mail: a@email.com
  tasks:
    - name: printing URL variable
      ansible.builtin.debug:
        msg: URL - {{url}}

    - name: printing MAil variable
      ansible.builtin.debug:
        msg: Mail - {{mail}}
